### ISSUE TITLE
Differences that need resolution

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-shaders#1]
Eventually there should be no appearances of `#if[n]def MAPBOX_GL_JS` in the shader sources.
- [x] missing in native: ["#mapbox pragma" commands support](https://github.com/mapbox/mapbox-gl-native/pull/5174)
- [x] missing in native: [overdraw inspector](https://github.com/mapbox/mapbox-gl-js/pull/2489)
- [x] circle
  - [x] missing in native: [convert mat4 exMatrix to a vec2 extrudeScale](https://github.com/mapbox/mapbox-gl-shaders/commit/a8d549b7a41540d3a99767975ff1b7b18a6010e9)
  - [x] missing in native: [Enabled data-driven styling for circle-radius](https://github.com/mapbox/mapbox-gl-shaders/commit/4356e41fa657837904d189e604468617ee601ddb)
  - [x] missing in native: [Reduce shader boilerplate, refactor "Bucket"](https://github.com/mapbox/mapbox-gl-shaders/commit/7d3da8f1914954fd96f305b7116cfd127a616551)
- [x] collisionbox
- [x] debug
- [x] fill
  - [x] missing in native: [separate u_opacity from u_color](https://github.com/mapbox/mapbox-gl-shaders/commit/0d3412519618a3a1672db9fa21f96f90070cf84c)
  - [x] missing in js: [Use glClear to draw solid background fills if they are the bottommost layer](https://github.com/mapbox/mapbox-gl-js/issues/2773)
- [x] icon
  - [x] missing in native: [convert mat4 exMatrix to a vec2 extrudeScale](https://github.com/mapbox/mapbox-gl-shaders/commit/a8d549b7a41540d3a99767975ff1b7b18a6010e9)
- [x] line
  - [x] missing in native: [separate u_opacity from u_color](https://github.com/mapbox/mapbox-gl-shaders/commit/0d3412519618a3a1672db9fa21f96f90070cf84c)
  - [x] missing in native: [combine line-width and line-gap-width in shader](https://github.com/mapbox/mapbox-gl-shaders/commit/a9559e911b11a155135888f733a96e5110f8cef6)
- [x] linepattern
  - [x] missing in native: [combine line-width and line-gap-width in shader](https://github.com/mapbox/mapbox-gl-shaders/commit/a9559e911b11a155135888f733a96e5110f8cef6)
  - [x] [minor organic difference](https://github.com/mapbox/mapbox-gl-shaders/blob/4a567b438be303fbbf13e5ddf49d72d8debd811d/src/linepattern.vertex.glsl#L78-L82)
- [x] linesdfpattern
  - [x] missing in native: [separate u_opacity from u_color](https://github.com/mapbox/mapbox-gl-shaders/commit/0d3412519618a3a1672db9fa21f96f90070cf84c)
  - [x] missing in native: [combine line-width and line-gap-width in shader](https://github.com/mapbox/mapbox-gl-shaders/commit/a9559e911b11a155135888f733a96e5110f8cef6)
- [x] outline
  - [x] missing in native: [separate u_opacity from u_color](https://github.com/mapbox/mapbox-gl-shaders/commit/0d3412519618a3a1672db9fa21f96f90070cf84c)
- [x] outlinepattern
  - [x] missing in native: [separate pattern size from draw-time variables](https://github.com/mapbox/mapbox-gl-shaders/commit/48d7f2dc06a2be1e95f800db6d00acffb1a0fd47)
- [x] pattern
  - [x] missing in native: [separate pattern size from draw-time variables](https://github.com/mapbox/mapbox-gl-shaders/commit/48d7f2dc06a2be1e95f800db6d00acffb1a0fd47)
- [x] raster - native doesn't do crossfading (https://github.com/mapbox/mapbox-gl-native/issues/115):
  - [x] [crossfade raster tiles](https://github.com/mapbox/mapbox-gl-shaders/commit/4ce26ac17d65fa6cf70019260f291ac3d2e782de)
  - [x] [let raster tiles fade in over background](https://github.com/mapbox/mapbox-gl-shaders/commit/1b75abb18b8525d61f78a5eff6952bcf7a488a34) 
  - [x] [clean up raster shader](https://github.com/mapbox/mapbox-gl-shaders/commit/46805c40bbd8c1f4df69a54e5663c366081ca3c3)
- [x] sdf
  - [x] missing in native: [separate u_opacity from u_color](https://github.com/mapbox/mapbox-gl-shaders/commit/0d3412519618a3a1672db9fa21f96f90070cf84c)
  - [x] missing in native: [convert mat4 exMatrix to a vec2 extrudeScale](https://github.com/mapbox/mapbox-gl-shaders/commit/a8d549b7a41540d3a99767975ff1b7b18a6010e9)
  - [x] missing in js: [don't clip glyphs with the frustum](https://github.com/mapbox/mapbox-gl-shaders/commit/c4093b52054b72d56fa97da9b3ad3fb2e261ab11) (https://github.com/mapbox/mapbox-gl-native/pull/2081)

Note that the above links are to commits imported into gl-shaders from gl-js and gl-native: they include the shader changes, but not corresponding .js or .cpp changes. When porting, you'll want to loop up the original commit to see the related changes to .js or .cpp files.

**Comment by jfirebaugh** [comment]
@kkaefer Can you tell me about https://github.com/mapbox/mapbox-gl-native/commit/e2fadf3157561456c0bc7b57a4e402d965194270? This is the one change I could find that was made in gl-native and not ported to gl-js, and it looks like it could be tricky to port because of conflicting changes to the sdf shader coming from the gl-js side. (cc @ansis)

**Comment by jfirebaugh** [comment]
Rough priorities for remaining convergence work:
- Reconcile [minor remaining difference](https://github.com/mapbox/mapbox-gl-shaders/blob/4a567b438be303fbbf13e5ddf49d72d8debd811d/src/linepattern.vertex.glsl#L78-L82) in linepattern shader. (Probably just pick one of the two lines, but I'm not sure which is preferable. cc @ansis)
- Port to native: [convert mat4 exMatrix to a vec2 extrudeScale](https://github.com/mapbox/mapbox-gl-shaders/commit/a8d549b7a41540d3a99767975ff1b7b18a6010e9). In the sdf shader, it needs to be reconciled with [don't clip glyphs with the frustum](https://github.com/mapbox/mapbox-gl-shaders/commit/c4093b52054b72d56fa97da9b3ad3fb2e261ab11) (https://github.com/mapbox/mapbox-gl-native/pull/2081).
- Port to native: [separate pattern size from draw-time variables](https://github.com/mapbox/mapbox-gl-shaders/commit/48d7f2dc06a2be1e95f800db6d00acffb1a0fd47). This will hopefully be straightforward for someone who understands the math.
- Minimize remaining differences in circle shader, short of requiring DDS implementation in gl-native.
- Launch DDS work in gl-native.
- Port raster cross-fading to native (https://github.com/mapbox/mapbox-gl-native/issues/115, low priority)

**Comment by brunoabinader** [comment]
Circle shader update is happening in https://github.com/mapbox/mapbox-gl-shaders/pull/4 and https://github.com/mapbox/mapbox-gl-native/pull/5191. Remaining #ifdefs in circle shader depends on https://github.com/mapbox/mapbox-gl-native/issues/5174.

**Comment by brunoabinader** [comment]
Icon/SDF shader update: https://github.com/mapbox/mapbox-gl-shaders/pull/5 and https://github.com/mapbox/mapbox-gl-native/pull/5196.

**Comment by brunoabinader** [comment]
Pragma commands for GL Native: #6 and https://github.com/mapbox/mapbox-gl-native/pull/5174.

**Comment by brunoabinader** [comment]
Line-pattern: [minor organic difference](https://github.com/mapbox/mapbox-gl-shaders/blob/4a567b438be303fbbf13e5ddf49d72d8debd811d/src/linepattern.vertex.glsl#L78-L82) fixed in https://github.com/mapbox/mapbox-gl-test-suite/pull/107, https://github.com/mapbox/mapbox-gl-shaders/pull/17, https://github.com/mapbox/mapbox-gl-js/pull/2724 & https://github.com/mapbox/mapbox-gl-native/pull/5327.

**Comment by brunoabinader** [comment]
[native] Separate pattern size from draw-time variables: #19, https://github.com/mapbox/mapbox-gl-test-suite/issues/112, https://github.com/mapbox/mapbox-gl-native/pull/5357 & https://github.com/mapbox/mapbox-gl-js/pull/2743.

**Comment by brunoabinader** [comment]
[native] Overdraw inspector mode: https://github.com/mapbox/mapbox-gl-native/pull/5403

**Comment by mourner** [comment]
Seems like everything is covered — no implementation-specific ifdefs left.
