### ISSUE TITLE
Put common preamble in "util.glsl"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-shaders#2]
This preamble is in every shader. We can simplify our code by moving it to `util.glsl`, which is included in every other shader. 

``` glsl
#ifdef GL_ES
precision mediump float;
#else
#define lowp
#define mediump
#define highp
#endif
```

ref https://github.com/mapbox/mapbox-gl-shaders/commit/93e3a7b62ee252b7843515c01d16af7958d39580#commitcomment-17604999

**Comment by jfirebaugh** [comment]
Note that fragment shaders use `precision mediump float;` while vertex shaders use `precision highp float;`.
