### ISSUE TITLE
Npm package unpublished?

### ISSUE THREAD

**Issue by kachkaev** [mapbox/mapbox-gl-shaders#20]
https://www.npmjs.com/package/mapbox-gl-shaders started to return 404 recently.
![404](https://cloud.githubusercontent.com/assets/608862/16771144/5a024d16-4847-11e6-83e5-298b25b40d49.png)

**UPD:** Actually it looks like the package never was on npm. Why not to publish it?

**Comment by kachkaev** [comment]
Asked to publish this package on npm in https://github.com/mapbox/mapbox-gl-js/issues/2856.

**Comment by jfirebaugh** [comment]
See https://github.com/mapbox/mapbox-gl-js/issues/2856#issuecomment-232116312.
