### ISSUE TITLE
Rationalize names

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-shaders#26]
Each name should start with the layer type the shader is used for. Words should be separated with underscores.
- `icon` ⇢ `symbol_icon`
- `sdf` ⇢ `symbol_sdf`
- `linepattern`  ⇢ `line_pattern`
- `linesdfpattern` ⇢ `line_sdf_pattern`
- `outline` ⇢ `fill_outline`
- `outlinepattern` ⇢ `fill_outline_pattern`
- `pattern` ⇢ `fill_pattern`

**Comment by mollymerp** [comment]
fwiw`pattern` and `fill` shaders are also used for background layers.

**Comment by jfirebaugh** [comment]
Correct -- one way to think of a  "background" layer is essentially as a fill layer with a single source feature covering the whole tile.
