### ISSUE TITLE
Line SDF vertex shader is missing opacity pragmas

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-shaders#37]
line_sdf.vertex.glsl is missing

```
#pragma mapbox: define lowp float opacity
```

and 

```
    #pragma mapbox: initialize lowp float opacity
```

This likely means that combinations of `line-opacity` and `line-dasharray` are not working.

cc @mollymerp

**Comment by mollymerp** [comment]
It doesn't look like it was in the `line_sdf.vertex` shader prior to the most recent changes: https://github.com/mapbox/mapbox-gl-shaders/pull/24/files#diff-aa94bda93aef8346b98c28a8add0d6d2

I'm not sure I understand where the vertex shader would use opacity?

A visual check shows that `line-opacity` + `line-dasharray` is working as expected in studio.

**Comment by jfirebaugh** [comment]
Try with a data-driven opacity value.

**Comment by mollymerp** [comment]
Ah! Yep -- confirmed. I'll make a PR.
