### ISSUE TITLE
Document how #pragmas work

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-shaders#7]
We need some documentation about how `#pragma mapbox` works, so that new developers encountering it can gain an understanding without needing to reverse engineer the gl-js and gl-native source.

@lucaswoj @brunoabinader, can you please coordinate on this?

**Comment by brunoabinader** [comment]
@jfirebaugh sure, do you have a specific place in mind? We can add a `README.md` to this repository with this kind of information.

**Comment by jfirebaugh** [comment]
Yeah, README.md would be great.
