### ISSUE TITLE
Include type as part of #pragma define?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-shaders#8]
See [this special case](https://github.com/mapbox/mapbox-gl-native/blob/af65da1ad79d760481379e20367c5977916f1a57/scripts/build-shaders.py#L33) in the gl-native #pragma implementation, and the FIXME above.

Should the type (`vec4` or `float`) be a part of the `#pragma` declaration itself, so that the heuristic isn't necessary?

cc @lucaswoj @brunoabinader

**Comment by brunoabinader** [comment]
Agreed @jfirebaugh @lucaswoj - this simplifies a lot of assumptions we'd previously need to have.

**Comment by brunoabinader** [comment]
Copying @lucaswoj's [comment](https://github.com/mapbox/mapbox-gl-native/commit/af65da1ad79d760481379e20367c5977916f1a57#commitcomment-17718182) here:

> #pragma mapbox: define color lowp vec4
> #pragma mapbox: initialize color lowp vec4
> 
> or maybe we should switch to 👇 for better consistency with glsl
> 
> #pragma mapbox: define lowp vec4 color
> #pragma mapbox: initialize lowp vec4 color

I prefer the latter. We also need to specify what is the name of the incoming uniform variable when these are not the same e.g. `outline_color`.  Do we want to add it as an additional param like the example below?

```
#pragma mapbox: define lowp vec4 outline_color color
#pragma mapbox: initialize lowp vec4 outline_color color
```

**Comment by lucaswoj** [comment]
I renamed the incoming uniform variable to `outline_color` in GL JS. The intent is to have a unique mapping between uniform names and buffer attributes (and style properties) (`fill-color` -> `color`, `fill-outline-color` -> `outline_color`). 

Can we rename the uniform to `outline_color` in GL Native?

**Comment by brunoabinader** [comment]
> Can we rename the uniform to outline_color in GL Native?

Yes 👍
